services:
  server:
    image: curoviyxru/uselessprogram2:server
  client:
    image: curoviyxru/uselessprogram2:client
    depends_on:
      server:
        condition: service_started
    deploy:
      replicas: 20